[package]
name = "limitpush" # Todo
version = "0.1.0"
authors = ["heydocode <heydocode@outlook.fr>"] # Todo
edition = "2021"
publish = false
exclude = ["dist", "build", "assets", "credits"]

[workspace]
members = [
    "crates/audio", 
    "crates/camera_system", 
    "crates/debug", 
    "crates/player", 
    "crates/states", 
    "crates/ui", 
    "crates/window_manager", 
    "crates/world",
    "mobile"
]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true

[profile.dist]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
strip = true

[features]
default = ["dev"]
dev = [
    "debug/dev"
]

[dependencies]
# Bevy Engine
bevy = { version = "*", default-features = false, features = [
    # "animation",
    # "bevy_state",
    # "bevy_color",
    # "bevy_gilrs",
    # "bevy_scene",
    # "bevy_winit",
    # "bevy_core_pipeline",
    # "bevy_pbr",
    # "bevy_gltf",
    # "bevy_render",
    # "bevy_sprite",
    # "bevy_text",
    # "bevy_ui",
    # "multi_threaded",
    # "png",
    # "jpeg",
    # "hdr",
    # "x11",
    # "bevy_gizmos",
    # "tonemapping_luts",
    # "smaa_luts",
    # "default_font",
    # "webgl2",
    # "sysinfo_plugin"
] }

audio = { path = "crates/audio" }
camera_system = { path = "crates/camera_system" }
debug = { path = "crates/debug" }
player = { path = "crates/player" }
states = { path = "crates/states" }
ui = { path = "crates/ui" }
window_manager = { path = "crates/window_manager" }
world = { path = "crates/world" }

# Synchronize with Bevy dependencies for window management and image loading
winit = { version = "0.30.5", default-features = false }
image = { version = "0.25.4", default-features = false }
bevy_transform_interpolation = { git = "https://github.com/Jondolf/bevy_transform_interpolation" }
avian3d = "0.1.2"

[build-dependencies]
embed-resource = "2.5.0"
