[package]
name = "debug"
version = "0.1.0"
edition = "2021"

[features]
dev = [
    "avian-debug",
    "diagnostics-logs",
]

avian-debug = []
diagnostics-logs = []

[dependencies]
bevy = { version = "*", default-features = false, features = [
    "animation",
    "bevy_state",
    "bevy_color",
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "multi_threaded",
    "png",
    "jpeg",
    "hdr",
    "x11",
    "bevy_gizmos",
    "tonemapping_luts",
    "smaa_luts",
    "default_font",
    "webgl2",
    "sysinfo_plugin"
] }
avian3d = "0.1.2"
bevy_mod_debugdump = "0.11.1"

bevy-inspector-egui = { version = "0.27.0", default-features = false }
bevy_egui = { version = "0.30.0", default-features = false, features = [
    "render"
]}

# Here we want it only on desktop builds
[target.'cfg(not(any(target_os = "ios", target_os = "android", target_family = "wasm")))'.dependencies]
bevy-panic-handler = "3.0.0"