[package]
name = "static_obj"
version = "0.1.0"
edition = "2021"
description = "Handles all static (= which don't move) objects/entities"

[dependencies]
data = { path = "../data" }
dep_reexp = { path = "../dep_reexp", features = ["bevy_pbr"]}