[package]
name = "states"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", default-features = false }
bevy_asset_loader = "0.21.0"
bevy_kira_audio = "0.20.0"
bevy_pipelines_ready = "0.4.0"