[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", default-features = false }
bevy_kira_audio = "0.20.0"

# Internal crates
# Avoid them to escape cyclic dependencies
states = { path = "../states"} # Dependency crate (= safe)